# =============================================================================
# BLOCO 1 - IMPORTS E CONFIGURAÇÃO DO BANCO (SUPABASE / RENDER / LOCAL)
# =============================================================================
import streamlit as st
import pandas as pd
import os
import time
from datetime import datetime
from sqlalchemy import create_engine, text

try:
    DATABASE_URL = os.getenv("DATABASE_URL") or st.secrets.get("DATABASE_URL")
except Exception:
    DATABASE_URL = os.getenv("DATABASE_URL") or ""

if not DATABASE_URL:
    DATABASE_URL = "sqlite:///campanha.db"

if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

IS_SQLITE = "sqlite" in DATABASE_URL

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if IS_SQLITE else {},
    pool_pre_ping=not IS_SQLITE,
)

# =============================================================================
# BASE 606 BALANCEADA - 101 CADA - ORDENADA POR SPEND
# =============================================================================
DADOS_606_BALANCEADO = [
("52.377.862 LARISSA FRAGA DE JESUS", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 385300.0),
("ALPHA GROUP COMERCIO DE EQUIPAMENTO", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 17847.0),
("AMAPA-LOC LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 26100.0),
("ATIVA RADIOCOMUNICACAO LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 30904.0),
("AUTOMAFIT NE SOLUCOES ELETRICAS E P", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 20855.0),
("BARTO ELETRONICA LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 817.0),
("BR-INOVA INDUSTRIA E COMERCIO DE PO", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 1007929.0),
("CENTRAL DAS BOMBONAS", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 750.0),
("DBL SERVICOS HIDRAULICOS LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 2218.0),
("DES VITORIA ALUGUEL DE", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 2672.0),
("DIVEK INDUSTRIA E COMERCIO LTDA", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 19957.0),
("DOISERRES VIANNA CONFECCOES LTDA", "WALDECIR MARQUES", "NORDESTE + OUTROS", 97701.0),
("ENGEGUS SOLUCOES EM ENGENHARIA LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 22300.0),
("ENGELC AMBIENTAL LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 12400.0),
("ERMMESON HUGO DOS SANTOS SILVA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 2970.0),
("FCG COMERCIODEFERRAMENTASLTDA", "WALDECIR MARQUES", "NORDESTE + OUTROS", 347667.0),
("GIVANILDO TIBURTINO DE LIRA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 16500.0),
("GL ACABAMENTOS CONSTRUTIVOS LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 11498.0),
("IDEAL STEEL COMERCIO DE FERRO E ACO", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 125995.0),
("IJC MANUTENÇÃO E INSTALAÇÕES LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 14048.0),
("IRISI INDUSTRIA E COMERCIO DE ARTEF", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 215033.0),
("JOZIMAR SANTOS DA SILVA", "WALDECIR MARQUES", "NORDESTE + OUTROS", 57527.0),
("JR FERRAMENTARIA LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 80972.0),
("LAJE FORTE MATERIAIS DE CONSTRUCAO", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 1341.0),
("MA PRODUCOES LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 2400.0),
("MAIS TREINAMENTOS E SEGURANCA DO TR", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 4900.0),
("MARIA CECILIA PEREIRA ANDRADE", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 6000.0),
("MARILIA RAFAELLA SOARES FARIAS", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 35875.0),
("MAXSAFETY BRASIL COM DE PRODUTOS IN", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 404540.0),
("MC COMERCIO E SERVICOS DE", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 11686.0),
("MCN SOLUCOES METROLOGICAS LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 165.0),
("METALURGICA IDEAL LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 9680.0),
("MODERNA SOLUÇÕES COM. E SERV. DE PR", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 7450.0),
("MOVITORQUE SISTEMAS HIDRAULICOS E P", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 1683.0),
("MOVITRACAO EQUIPAMENTOS LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 123302.0),
("MUNDO DAS CORREIAS LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 3000.0),
("NEW ENERGY SOLUCOES EM ENERGIA LTDA", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 158226.0),
("NUNES & NUNES ROLAMENTOS E PECAS LT", "WALDECIR MARQUES", "NORDESTE + OUTROS", 50928.0),
("OPEN VIA COMERCIAL LIMITADA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 2380.0),
("POLIACO SERVICOS DE MONTAGEM LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 2000.0),
("PROLOC LOCACOES DE MAQUINAS E FERRA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 15488.0),
("QUALIPANOS EPI LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 8190.0),
("QUALISEG CONSULTORIA LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 8661.0),
("RANCHO PIONEIRO SOLUCOES LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 9200.0),
("RECICLE SOLUCOES AMBIENTAIS LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 43400.0),
("SEMF SERVICOS METROLOGICOS LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 860.0),
("SENA E SENA COMERCIO E SERVICO LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 90890.0),
("SILVERESSES SOLUCOES EM SISTEMAS PA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 2954.0),
("SINALIZACAO BRASIL LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 1538.0),
("SUAPE PARAFUSOS MAQUINAS E", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 3575.0),
("TENAZ COMERCIAL DE PRUDPLASTICOS LT", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 58030.0),
("TOP LIMP SERVICOS LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 10066.0),
("UPGRADE COMERCIO DE PRODUTOS PARA S", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 4302.0),
("ACESSO TELECOMUNICACOES", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 34400.0),
("COMPARE SERVICOS DE MOTORES ELETRIC", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 29038.0),
("F G INFOTEC RECIFE EIRELI ME", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 92122.0),
("J M SILVA MAQUINAS E EQUIPAMENTOS L", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 19200.0),
("LLP COMERCIO E SERVICOS LTDA", "WALDECIR MARQUES", "NORDESTE + OUTROS", 9067.0),
("ORKAN INFORMATICA INDUSTRIAL LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 2550.0),
("R S DEDETIZACAO LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 12150.0),
("WRM MANUTENCAO DE MAQUINAS LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 9950.0),
("AFR INFO COMERCIO E SERVICOS DE INF", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 146777.0),
("CRISTIANE COMERCIO DE TINTAS", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 16032.0),
("FERREIRA FREIOS REPRESENTCOMERCIAL", "WALDECIR MARQUES", "NORDESTE + OUTROS", 12761.0),
("G.A LOCACOES DE EQUIPAMENTOS LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 856274.0),
("JOSE CARLOS DE SOUZA 58752080404", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 8450.0),
("MECSEG COM E SERV DE PRODUTOS ELETR", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 1593305.0),
("OUTLET HOME OFFICE PALMARES LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 3000.0),
("RECIFE METAIS COMERCIO DE MATERIAIS", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 5738.0),
("AGV TINTAS AUTOMOTIVAS LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 191098.0),
("DANIELA NASCIMENTO CABRAL", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 3220.0),
("FLEXBELT COMERCIAL DE CORREIAS E PO", "WALDECIR MARQUES", "NORDESTE + OUTROS", 62670.0),
("GISELLE M. GOMES", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 42150.0),
("KADISA INDUSTRIA E COMERCIO LTDA-ME", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 1620.0),
("PAPELARIA SANTA TEREZINHA LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 1215.0),
("RIBERFLOW COMERCIO E SERVICOS LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 1520.0),
("ALBERTO PROJETO DE SEGURANCA CONTRA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 7800.0),
("DES IPUTINGA ALUGUEL DE EQUIPAMENTO", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 4080.0),
("GREGORIO ALVES DE CASTRO", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 113397.0),
("HANNA PALACE HOTEL", "WALDECIR MARQUES", "NORDESTE + OUTROS", 88041.0),
("LEAL & SORIANO NEGOCIOS IMOBILIARIO", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 125246.0),
("PEDRO PAULO FERREIRA BRAZ LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 398.0),
("ROSANGELA DO C V S DA CUNHA ME", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 24784.0),
("A J MARTINS FILHO PARAFUSOS E FERRA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 1382.0),
("ACIONATECH SERVICOS TECNICOS LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 18587.0),
("AFIRET FABRICACAO E SERVICOS LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 10400.0),
("ANDERSON MANOEL DOS SANTOS BEZERRA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 4550.0),
("ARBA DE V REDONDA TECNINFORMLTDA", "WALDECIR MARQUES", "NORDESTE + OUTROS", 26552.0),
("ASTOR BRINDES COMERCIO E INDUSTRIA", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 61044.0),
("BRICIO AL VERDE MACAPA ALUGUEL DE E", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 1702.0),
("CADA CANTO DECORACOES LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 1178.0),
("CASA DO CONSTRUTOR", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 5600.0),
("CENTER EQUIPAMENTO E SERV ELETRICOS", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 184978.0),
("CLAUDIO GUILHERME MEDALHA DA SILVA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 91960.0),
("COBERPRO, MONTAGEM E MANUTENCAO DE", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 21000.0),
("COMERCIAL QUINTANILHA FITAS E ADESI", "WALDECIR MARQUES", "NORDESTE + OUTROS", 240888.0),
("DAF - AUTOMACAO LTDA", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 11720.0),
("DAVIDSON MICHAEL LIMA DA SILVA 0711", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 108000.0),
("EDUARDO ALVES DA SILVA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 1565.0),
("EGILDO ALVES DOS SANTOS", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 6300.0),
("ELEPLASFER INDUSTRIA E COMERCIO LTD", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 57277.0),
("ELIAS DO NASCIMENTO FONSECA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 800.0),
("ELIUDE DE SANTANA COSTA MONTEIRO LT", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 191.0),
("ENGESAC IND E RECICLAGEM EM GERAL L", "WALDECIR MARQUES", "NORDESTE + OUTROS", 1052321.0),
("GTR INFORMATICA LTDA", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 44648.0),
("HTM LOCACOES LTDA ME", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 48247.0),
("INDAIA COMERCIO DE PECAS E COMPONEN", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 3044.0),
("INDUSTRIA DE BORRACHAS FAPRIBOR LTD", "WALDECIR MARQUES", "NORDESTE + OUTROS", 305054.0),
("K N PALETES E CONSTRUCOES LTDA ME", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 470795.0),
("KELLY MARIA MARTINS DA SILVA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 37948.0),
("M DA C DE LIMA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 135798.0),
("MAC ANALISE AMBIENTAL LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 2430.0),
("MAURICIO LUZ GALLINARI JUNIOR", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 120698.0),
("METALURGICAONZE LIMITADA ME", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 6032.0),
("MICHELLE F. DA SILVA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 8353.0),
("MK2 PROMO COMDE PRODPROMOCEIRELI", "WALDECIR MARQUES", "NORDESTE + OUTROS", 24602.0),
("MOVTEC INDUSTRIA COMERCIO E SERVICO", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 7505.0),
("NASILDO PIMENTEL DE ARAUJO JUNIOR", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 34134.0),
("NORDESTE INVERSORES ELETRONICA INDU", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 10760.0),
("ORBITEC CONSULTORIA LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 13900.0),
("P LINS EMPREENDIMENTOS LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 12600.0),
("PINA OFFICE DESIGN LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 9570.0),
("POLIPOCOS SERVICOS EIRELI", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 8700.0),
("RAFAEL BELARMINO DA COSTA 162369474", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 2950.0),
("RBC IMPORTACAO E EXPORTACAO LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 3000.0),
("RS ALBUQUERQUE LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 18000.0),
("SALOMAO GLASS TEMP LTDA ME", "CAMILA CAROLINE DA SILVA", "NORDESTE + OUTROS", 376038.0),
("SEVERINO GALVAO", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 9932.0),
("TOP LAB AMBIENTAL LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 9456.0),
("VALERIA CRISTINA DA SILVA 711837314", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 85390.0),
("VAZAO LOCACAO DE COMPRESSORES", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 17945.0),
("VRI CONSULTORIA E ENGENHARIA LTDA", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 16000.0),
("WENDELL SOARES DO NASCIMENTO 053241", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 2250.0),
("WGIL COMERCIO E CONFECCOES DE BANDE", "WALDECIR MARQUES", "EXCLUSIVO NORDESTE", 3980.0),
("WR MAQUINAS LTDA", "CAMILA CAROLINE DA SILVA", "EXCLUSIVO NORDESTE", 4550.0),
("3S ELETRONICOS E COMERCIO", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 75.0),
("60.550.228 CAMILA FIRMINO GERALDO", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 1520.0),
("AG CONSTRUCOES TERRAPLANAGEM", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 274835.0),
("AGUSHOP COMERCIO DE ELETRONICOS", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 270.0),
("ALV DO BRASIL IND E COMERCIO DE MOL", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 540.0),
("ATERRADO REFRIGERACAO LTDA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 1533.0),
("BICHACO E CARVALHO", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 280.0),
("BJM INDUSTRIA E COMERCIO LTDA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 382412.0),
("BS DUTRA COMDE ROLAMENTOS ME", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 19132.0),
("CASA VITORIA DE BARRA DO PIRAI COM", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 16445.0),
("CIRURGICA BPIRAI COMMATERIAL", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 1226.0),
("CONSULAB CONSULTORIA E ENSAIOS DE", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 330233.0),
("DAYVISONN QUEIROZ SEPULVEDA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 980.0),
("DIREL COMERCIO ELETRICA LTDA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 4339.0),
("ECAE MATERIAL PARA CONSTRUCAO LTDA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 340.0),
("F. A. DE CAIRES  - FAC BALANCAS", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 755.0),
("FERNANDO CARIELLO NETO LTDA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 344142.0),
("FLAVIO DE CARVALHO DIST. DE BEBIDAS", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 3598.0),
("FRIDESC INDUSTRIA E COMERCIO DE EMB", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 19043.0),
("GABRIELA RODRIGUES DA SILVA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 590.0),
("HAMBOR COMERCIO E IMPORTACAO LTDA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 414.0),
("INFOSOM AUDIO E IMAGEM LTDA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 1000.0),
("J R A TOPOGRAFIA AGRIMENSURA E", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 18051.0),
("JOZE FLORES LTDAME", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 800.0),
("KMG SUPRALIM PRODUTOS DE HIGIENE LI", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 516.0),
("LCA ELETRICA E ILUMINACAO LTDA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 279.0),
("LOPES E MIRANDA CIA.LTDA.", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 2490659.0),
("LUMITEX COMERCIAL E SERVICOS LTDA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 4070.0),
("MADOQ COMERCIO E INDUSTRIA LTDA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 14774.0),
("MARIA CAROLINA LOPES CORREA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 3940.0),
("MECAPAR PRODUTOS PARA MANUT IND LTD", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 542.0),
("MERCURYS DA SILVA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 184.0),
("MODERNA PAPELARIA E LIVRARIA LTDA", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 21729.0),
("NEVES COMERCIO DE AUTOPECAS E ACESS", "CAMILA CAROLINE DA SILVA", "OUTROS CENTROS", 3651.0),
("OXIVR GASES INDUTRIAIS E", "WALDECIR MARQUES", "OUTROS CENTROS", 13230.0),
("PERFIL MARCAS E PATENTES E DIREITOS", "WALDECIR MARQUES", "OUTROS CENTROS", 20641.0),
("POUSADA LUAR DO SERTAO LTDA", "WALDECIR MARQUES", "OUTROS CENTROS", 4482.0),
("R G BARBOZA COMERCIO E SERVICOS LTD", "WALDECIR MARQUES", "OUTROS CENTROS", 1281.0),
("REIS & ALVES COMERCIO ELETRONICO LT", "WALDECIR MARQUES", "OUTROS CENTROS", 607.0),
("RODRIGO DA SILVA ANTUNES", "WALDECIR MARQUES", "OUTROS CENTROS", 270420.0),
("ROSANGELA SILVA E CIA LTDA ME", "WALDECIR MARQUES", "OUTROS CENTROS", 169.0),
("SCUDO OPTICO INDUSTRIAL EIRELI", "WALDECIR MARQUES", "OUTROS CENTROS", 895.0),
("SORT-RIO COMERCIO E REPRESENT LTDA", "WALDECIR MARQUES", "OUTROS CENTROS", 455.0),
("SYC FIRE LTDA", "WALDECIR MARQUES", "OUTROS CENTROS", 1689900.0),
("TI NEVES AUTO PECAS LTDA ME", "WALDECIR MARQUES", "OUTROS CENTROS", 555.0),
("TPX & EINFACH CONSULTORIA E", "WALDECIR MARQUES", "OUTROS CENTROS", 338300.0),
("ULTRASEG FERRAMENTAS SOLDAS E ABRAS", "WALDECIR MARQUES", "OUTROS CENTROS", 486.0),
("VENA CONTRACTA RIO - INDUSTRIA E CO", "WALDECIR MARQUES", "OUTROS CENTROS", 469.0),
("W R L LUBRIFICANTES LTDA", "WALDECIR MARQUES", "OUTROS CENTROS", 11442.0),
("49.890.398 NATHALY SOUZA DE JESUS", "WALDECIR MARQUES", "OUTROS CENTROS", 1520.0),
("61.777.663 INGRID SILVA DE SOUZA", "WALDECIR MARQUES", "OUTROS CENTROS", 1350.0),
("A B RODRIGUES LOCACOES DE MAQEQUIP", "WALDECIR MARQUES", "OUTROS CENTROS", 246974.0),
("ABOUTNET INFORMATICA LTDA", "WALDECIR MARQUES", "OUTROS CENTROS", 73980.0),
("AIR CONTROL AUTOMACAO LTDA", "WALDECIR MARQUES", "OUTROS CENTROS", 180.0),
("AMZ AUTOMACAO E TECNOLOGIA LTDA", "WALDECIR MARQUES", "OUTROS CENTROS", 900.0),
("ANTONIO MARCOS DOMINGOS 00401456706", "WALDECIR MARQUES", "OUTROS CENTROS", 64226.0),
("ATM INDUSTRIA COMERCIO E SERVICOS L", "WALDECIR MARQUES", "OUTROS CENTROS", 3350.0),
("BP LEAO COM MAT MEDICO HOSPITALARES", "WALDECIR MARQUES", "OUTROS CENTROS", 3476.0),
("BRAZLIGHT MATERIAL", "WALDECIR MARQUES", "OUTROS CENTROS", 97807.0),
("BW2 LIFTING INDUSTRIA E COMERCIO DE", "WALDECIR MARQUES", "OUTROS CENTROS", 125246.0),
("C S SAMPAIO MATERIAIS DE CONSTRUCAO", "WALDECIR MARQUES", "OUTROS CENTROS", 168.0),
("CASTELO CORREIAS E", "WALDECIR MARQUES", "OUTROS CENTROS", 329.0),
("CINTATEC ACESSORIOS PARA", "WALDECIR MARQUES", "OUTROS CENTROS", 84672.0),
("CJO LOJA DE VARIEDADES LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 92.0),
("D KENUPP CLER ME", "WALDECIR MARQUES", "OUTROS CENTROS", 214143.0),
("DENIS GOMES DE OLIVEIRA LTDA", "WALDECIR MARQUES", "OUTROS CENTROS", 540.0),
("DOURA IMPER IMPERMEABILIZANTES LTDA", "WALDECIR MARQUES", "OUTROS CENTROS", 4476.0),
("EB PEREIRA COM DE VED FILTROS E ACE", "WALDECIR MARQUES", "OUTROS CENTROS", 55296.0),
("EJB COMERCIO DE ROLAMENTOS EQUIPAME", "WALDECIR MARQUES", "OUTROS CENTROS", 65082.0),
("ELETROTECNICA MATTOS LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 11998.0),
("EQUILIBRIO PROMOCOES E PRODUCOES DE", "GILCIMAR SILVA", "OUTROS CENTROS", 100000.0),
("FAMA ARTIGOS", "GILCIMAR SILVA", "OUTROS CENTROS", 781.0),
("FLEX CARDS SISTEMAS DE IDENTIFICACA", "GILCIMAR SILVA", "OUTROS CENTROS", 4310.0),
("FORTE TRES RIOS VIGILANCIA", "GILCIMAR SILVA", "OUTROS CENTROS", 114958.0),
("FRIOPAR COMERCIAL LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 488.0),
("GEPRO ENGENHARIA LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 21573.0),
("GRUPO MULTI DO BRASIL LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 72250.0),
("H.S.A.", "GILCIMAR SILVA", "OUTROS CENTROS", 68000.0),
("HAGANE TECNOLOGIA EM ROLOS DE CONFO", "GILCIMAR SILVA", "OUTROS CENTROS", 120555.0),
("HIDRO ELETRICA VOLTA REDONDA LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 1360.0),
("IBR INDUSTRIA BRASILEIRA DE RECICLA", "GILCIMAR SILVA", "OUTROS CENTROS", 61192.0),
("INTERTAC COMPONENTES", "GILCIMAR SILVA", "OUTROS CENTROS", 605.0),
("IURI VIEIRA GOMEZ MASID PISOS E REV", "GILCIMAR SILVA", "OUTROS CENTROS", 53000.0),
("JAMILE ARAUJO TAKANO", "GILCIMAR SILVA", "OUTROS CENTROS", 72886.0),
("JC ARAUJO PEIXOTO BALANCAS ASSISTEN", "GILCIMAR SILVA", "OUTROS CENTROS", 19028.0),
("JULIANE DE MELO GIACHETTI", "GILCIMAR SILVA", "OUTROS CENTROS", 380.0),
("KALTHERM REFRIGERACAO LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 63500.0),
("KATZEN COMERCIO, SERVICOS E LOCACOE", "GILCIMAR SILVA", "OUTROS CENTROS", 240000.0),
("L. C. P. DA SILVA GRAFICA", "GILCIMAR SILVA", "OUTROS CENTROS", 3356.0),
("LCA TREINAMENTOS E CURSOS LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 45836.0),
("LDL SOLUÇÕES LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 102.0),
("LDR PINTURA LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 56209.0),
("LEA S GONCALVES MAT CONSTRUCAO", "GILCIMAR SILVA", "OUTROS CENTROS", 191201.0),
("LUCIANO PEDRO DE BARROS VIDRACARIA", "GILCIMAR SILVA", "OUTROS CENTROS", 450.0),
("LUMINOSOS CEUTH LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 143600.0),
("LUZIA GORETE QUIRINO GUARATINGUETA", "GILCIMAR SILVA", "OUTROS CENTROS", 1408.0),
("MADEIREIRA SANTO ANTONIO COMERCIO", "GILCIMAR SILVA", "OUTROS CENTROS", 112892.0),
("MAGI ACESSORIOS INDUSTRIAIS EIRELI", "GILCIMAR SILVA", "OUTROS CENTROS", 4575.0),
("MAJ HIDRAULICOS INDUSTRIA DE EQUIP.", "GILCIMAR SILVA", "OUTROS CENTROS", 74500.0),
("MARIANA MAXIMO PROENCA 42693860881", "GILCIMAR SILVA", "OUTROS CENTROS", 1140.0),
("MAV X TECNOLOGIA LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 105276.0),
("MEDEIROS E REZENDE MANGUEIRA E CONX", "GILCIMAR SILVA", "OUTROS CENTROS", 119523.0),
("MEGA 10 BENEFSERV E COMCORREIAS LTD", "GILCIMAR SILVA", "OUTROS CENTROS", 20466.0),
("MEGABYTE INFORMATICA LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 70622.0),
("METOUS SERV DE MEC E USINAGEM LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 73025.0),
("MGL INDUSTRIA COMERCIO E SERVICOS L", "GILCIMAR SILVA", "OUTROS CENTROS", 270.0),
("MODULO HS LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 13616.0),
("MR COME MANUTDE MAQINDEIRELI ME", "GILCIMAR SILVA", "OUTROS CENTROS", 106443.0),
("NEW DIAMOND PRODUTOS", "GILCIMAR SILVA", "OUTROS CENTROS", 4649.0),
("ONE INSPECOES E SOLUCOES", "GILCIMAR SILVA", "OUTROS CENTROS", 129156.0),
("P F G DA COSTA SERVIÇOS ADMINISTRAT", "GILCIMAR SILVA", "OUTROS CENTROS", 19842.0),
("PASCAL ENGENHARIA LTDA ME", "GILCIMAR SILVA", "OUTROS CENTROS", 114434.0),
("PNEUS ZERO E AUTO PECAS LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 800.0),
("POUSADA E RESTAURANTE ARARA LTDA ME", "GILCIMAR SILVA", "OUTROS CENTROS", 56097.0),
("POWER STYLLUS DOOR IND PORTAS E COR", "GILCIMAR SILVA", "OUTROS CENTROS", 76505.0),
("PRECISAO ABSOLUTA", "GILCIMAR SILVA", "OUTROS CENTROS", 16.0),
("PREMIUM MANUTENCAO E PINTURA LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 154038.0),
("R.N. DE SOUZA", "GILCIMAR SILVA", "OUTROS CENTROS", 3090.0),
("RELOF COZINHAS PROFISSIONAIS", "GILCIMAR SILVA", "OUTROS CENTROS", 3860.0),
("ROVINGLITE INDUSTRIA", "GILCIMAR SILVA", "OUTROS CENTROS", 77418.0),
("RTS EPI VR LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 156.0),
("SERGIO F. ALVES PINHEIRO", "GILCIMAR SILVA", "OUTROS CENTROS", 1070.0),
("SERMOLD MECANICA INDUSTRIAL", "GILCIMAR SILVA", "OUTROS CENTROS", 120205.0),
("SIMAQ COMERCIO DE MAQUINAS LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 178188.0),
("SOMAR CONSTRUCAO LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 56550.0),
("SPEED VALLEY TECNOLOGIA E SERVICOS", "GILCIMAR SILVA", "OUTROS CENTROS", 80316.0),
("STALX PRODUTOS METALURGICOS LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 4428.0),
("T. C. P.  KONDO", "GILCIMAR SILVA", "OUTROS CENTROS", 158.0),
("TCW SERVICOS DE COMERCIO", "GILCIMAR SILVA", "OUTROS CENTROS", 77882.0),
("TLR COMERCIO DE ALIMENTOS", "GILCIMAR SILVA", "OUTROS CENTROS", 1310.0),
("TRILHOS MUNDIAL LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 203099.0),
("TRIUNFO EQUIPAMENTOS", "GILCIMAR SILVA", "OUTROS CENTROS", 93846.0),
("UNI TERRA TERRAPLENAGEM LTDA ME", "GILCIMAR SILVA", "OUTROS CENTROS", 13300.0),
("USICAP USINAGEM LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 172170.0),
("VARGEM ALEGRE MATERIAL", "GILCIMAR SILVA", "OUTROS CENTROS", 176725.0),
("VERNILLE COMERCIO E SERVICO DE MADE", "GILCIMAR SILVA", "OUTROS CENTROS", 1460.0),
("VIACOMP TECNOLOGIA DA", "GILCIMAR SILVA", "OUTROS CENTROS", 59930.0),
("VITORIA DE B DO PIRAI COMDE TINTAS", "GILCIMAR SILVA", "OUTROS CENTROS", 49013.0),
("VIVIANE PEREIRA MOTTA LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 222721.0),
("WALDECY MOTTA ME", "GILCIMAR SILVA", "OUTROS CENTROS", 5058.0),
("WEROIL LUBRIFICANTES EIRELI", "GILCIMAR SILVA", "OUTROS CENTROS", 90492.0),
("YOLI LOCACAO DE EQUIPAMENTOS LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 167650.0),
("50.316.726 RUBEN LIMEIRA DOS SANTOS", "GILCIMAR SILVA", "OUTROS CENTROS", 3900.0),
("61.617.378 WALLACE MEIRELES SANTANA", "GILCIMAR SILVA", "OUTROS CENTROS", 6650.0),
("63.494.023 CAROLINA BEATRIZ PIRES G", "GILCIMAR SILVA", "OUTROS CENTROS", 1520.0),
("ALINE CRISTINA BISEWSKI", "GILCIMAR SILVA", "OUTROS CENTROS", 123.0),
("ANDERSON", "GILCIMAR SILVA", "OUTROS CENTROS", 263.0),
("ARAUJO & REZENDE LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 9900.0),
("ASTG BRNDES E DISTRIBUIDORA LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 10384.0),
("AUTO TECH REPARADORA VEICULOS LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 10761.0),
("B&F LABORATORIO DE METROLOGIA LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 16121.0),
("BACKSTAGE PROD. LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 9500.0),
("BARRA EXPRESS SERVICOS", "GILCIMAR SILVA", "OUTROS CENTROS", 9920.0),
("BRAF ARQUITETURA LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 15500.0),
("BRUNO E CHAVES COMRECP E SERVIC", "GILCIMAR SILVA", "OUTROS CENTROS", 6829.0),
("CAIO GABRIEL SOUZA SILVA", "GILCIMAR SILVA", "OUTROS CENTROS", 550.0),
("CAIOBRÁS COMÉRCIO E LOCAÇÕES LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 7230.0),
("CENTRAL DAS BATERIAS LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 7679.0),
("CENTRO FOTOGRAFICO BARRA DO PIRAI L", "GILCIMAR SILVA", "OUTROS CENTROS", 1350.0),
("CIRCULO 1 AUTOMOBILE LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 8000.0),
("CLAUDIO DOS SANTOS ANGLER", "GILCIMAR SILVA", "OUTROS CENTROS", 5600.0),
("DENTAL PEIXOTO COMERCIO", "GILCIMAR SILVA", "OUTROS CENTROS", 52.0),
("DRI-TATA COMERCIAL LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 265.0),
("E ASUPRIMENTOS PARA IMPRESSORAS EIR", "GILCIMAR SILVA", "OUTROS CENTROS", 7441.0),
("EBM EMPRESA BRASILEIRA DE METROLOGI", "GILCIMAR SILVA", "OUTROS CENTROS", 7300.0),
("EMPILHA TETRA COM DE PECAS E SERV L", "GILCIMAR SILVA", "OUTROS CENTROS", 5354.0),
("ERCO MATERIAIS PARA ESCRITORIO LTDA", "GILCIMAR SILVA", "OUTROS CENTROS", 8842.0),
("ETSANTOS NERVINO COM DE INFORMATICA", "GILCIMAR SILVA", "OUTROS CENTROS", 1030.0),
("F. M. DOS SANTOS FABRICACAO E COM M", "GILCIMAR SILVA", "OUTROS CENTROS", 10000.0),
("FATIMA CRISTINA BARBOSA MARANHAO CE", "GILCIMAR SILVA", "OUTROS CENTROS", 4527.0),
("FEROLI LOCACAO E COMERCIO DE MAQUIN", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 10647.0),
("FLORICULTURA NOBRE LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 415.0),
("FORT VALLE", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 8412.0),
("FUNERARIA CHEREM", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 4760.0),
("GMAX SERVICOS", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 14930.0),
("HILLCO LOCAÇÃO E COMERCIO", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 313.0),
("INFINITY ACRILICOS E COM VISUAL LTD", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 7740.0),
("IRMAOS PELLEGRINI LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 4495.0),
("IT LABEL ETIQUETAS E EMBALAGENS EIR", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 5319.0),
("IVAN MACHULA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 10000.0),
("JAHIDRAULICA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 6984.0),
("JG COMERCIO E MANUTENCAO LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 1191.0),
("JG CONSULTORIA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 6918.0),
("JUMACOL JUPARANA MATERIAIS DE CONST", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 4990.0),
("JV MONTAGENS", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 8500.0),
("KARINA LAMONIER DA SILVA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 5985.0),
("L.F. COELHO DOMINGOS", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 1440.0),
("LAZARO CESAR DA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 9026.0),
("LEANDRO CORREA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 1179712.0),
("LUCIENE CANDIDO ROSA 03458706623", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 409.0),
("M & S ESCOVAS INDUSTRIAIS LTDA EPP", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 10800.0),
("M.M. MOUTINHO USINAGEM LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 7000.0),
("MAIS LAR DECOR LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 6671.0),
("MANLOG MANUTENÇÕES PLANEJADAS LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 6500.0),
("MAQCARRACA VENDA E MANUTENCAO DE MA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 721.0),
("MASTER COPY REPROGRAFIA LTDA - ME", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 7000.0),
("MAURA CONCEICAO SATYRO - ME", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 12796.0),
("MEGA TELAS COMERCIO DE VAREJISTA LT", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 282.0),
("MELO E PONTES MOVEIS LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 7000.0),
("MID AUTOMACAO E ELETRICA COM E SERV", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 5429.0),
("MINI CENTER PLANTAS", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 10497.0),
("MOKKA COMDE BENS DE CONSUMO EIRELLI", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 9639.0),
("MP COMERCIO DE PNEUS INDUSTRIAIS E", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 14193.0),
("MR SERVICOS DE FACILITIES LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 10300.0),
("MSVICENTE LOCACOES E SERVICOS LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 6357.0),
("NIQUELTEM COMERCIAL ELETRICA LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 282.0),
("NOVA SYSTEM COMERCIO E SERVICOS LTD", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 7118.0),
("P C DE MATOS JUNIOR INSTALACAO", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 6300.0),
("PANIZZI & CARVALHO COMERCIO DE PECA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 3730.0),
("PATRICIA ELIAS DO NASC BENTO 07599", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 10000.0),
("PAVESA COMERCIO", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 5831.0),
("PENSAR PUBLICIDADE LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 10190.0),
("PFE DOOR INSTALACOES E MANUTENCOES", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 6500.0),
("POLI INDUSTRIA E COMERCIO", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 3500.0),
("PRELAJE IND E COM LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 4390.0),
("PROVISIO MOBILIARIO COMERCIO E INDU", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 9875.0),
("QUADTEK MAQUINAS E SERVICOS LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 8000.0),
("RAFAEL B DA SILVA COM E IMP", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 245.0),
("RAFAEL GONÇALVES DUARTE - ME", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 9800.0),
("RENATA MARIA VASCONCELOS DIAS", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 3200.0),
("RESIST COMERCIO DE RESISTENCIA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 7177.0),
("RIO BRAS COMERCIO DE PECAS LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 5708.0),
("ROYAL IMPORT E DISTRIB LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 8313.0),
("SAFE 4 LIFE SERVICOS NAUTICOS LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 4692.0),
("SALVICOM COMERCIO E SERVICOS DE PRO", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 8918.0),
("SHIDO SERVICOS E SAUDE LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 600.0),
("SIVIS TECNOLOGIA LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 9995.0),
("STAR FORT MATERIAIS DE", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 17429.0),
("TANIA MARIA FERREIRA MORAES SOCIEDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 649.0),
("TOP HOSE COMERCIO DE MANGUEIRAS LTD", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 16161.0),
("TSD ARQUITETURA PROMOCIONAL LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 8690.0),
("UNIPEDRAS BENEFIC.E COM DE MARMORES", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 3539.0),
("VENTURINI CONSULTORIA E ARQUITETURA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 4750.0),
("VETOR COMERCIO E", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 10813.0),
("WASABI FILMES ALINE DE OLIVEIRA LTD", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 12000.0),
("1206 TINTAS COM DE TINTAS BARRA DO", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 212.0),
("3A BRASILTEC COMERCIO E", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 5894.0),
("54.193476 RENATA DE MACEDO FIGUEIRA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 4656.0),
("A L MARINATO COM. DE PROD. FOTOGRAF", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 121.0),
("A3 AUTOMACAO E SERVICOS LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 28199.0),
("ABRACE AVALIACOES BRASIL DA CONFORM", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 24969.0),
("ALMOTEC COMERCIAL LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 672.0),
("ALOYSIO DRUMOND CASSERES FILHO SOLU", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 38235.0),
("AMJ COMERCIO DE FERRAMENTAS IND LTD", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 48537.0),
("AO PRECO FIXO PAPELARIA LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 240.0),
("APEX INDUSTRIAL E SERVICOS LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 30000.0),
("B C BREVES EIRELI", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 46740.0),
("BARBOSA & FILHOS TERRAPLENAGEM E LO", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 4500.0),
("BOSI ENGENHARIA E FUNDACOES LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 40000.0),
("BR LEDS COMERCIO E SERVICOS EIRELI", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 29065.0),
("BRAZAO COMERCIAL", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 1328.0),
("CAIXAS ERIKA MELKOT LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 478.0),
("CARIELLO & ALMEIDA LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 31435.0),
("CERTECKI EQUIPAMENTOS INDUSTRIAIS L", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 565.0),
("CLAUDIO MARCIO ALVES FLORES E PLANT", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 32243.0),
("CLAUDIO OSNY LINDENMEYER", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 11408.0),
("CONTERMAQ LOCACAO DE EQUIPAMENTOS E", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 47250.0),
("D F M MONTEIRO SOLUCOES EM SEGTRABA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 27357.0),
("DELTA ASSESSORIA ADUANEIRA LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 44813.0),
("DIEDRO INDE COMDE MAQLTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 392.0),
("DRIKATEC FERRAMENTAS", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 816.0),
("EDITORA E EVENTOS", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 49000.0),
("ELETROFONTES REFRIGERACAO LTDA ME", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 46927.0),
("ERGOMOBILE MOVEIS LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 40741.0),
("EV TOPOGRAFIA LTDA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 16970.0),
("FABIANO A. SOUZA", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 46000.0),
("FAVORITA IMPORTACAO E DISTRIBUICAO", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 154.0),
("FERNANDA BRITTO COUTINHO 0962689378", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 34540.0),
("FP BOMBEAMENTO DE CONCRETO E SERVIC", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 3500.0),
("FUSICON FUSIVEIS E ACESS EIRELI", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 5269.0),
("GRUPO ANDRADE MANUTENCAO DE MOTORES", "MARIA FATIMA", "OUTROS CENTROS", 33885.0),
("H E ASSESSORIA EM ENERGIA LTDA EPP", "MARIA FATIMA", "OUTROS CENTROS", 32909.0),
("HELIO MARINE SERVICE LTDA", "MARIA FATIMA", "OUTROS CENTROS", 27863.0),
("HIDRAUMAX COMERCIAL EIRELI", "MARIA FATIMA", "OUTROS CENTROS", 36450.0),
("HOTEL PALMEIRA IMPERIAL MARQUES DE", "MARIA FATIMA", "OUTROS CENTROS", 900.0),
("HUB DA CONSTRUCAO MIDIA", "MARIA FATIMA", "OUTROS CENTROS", 27500.0),
("IND METALURGICA COROADOS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 22402.0),
("ISAMAND COMERCIO DE TINTAS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 16480.0),
("JBL INFORMATICA LTDA", "MARIA FATIMA", "OUTROS CENTROS", 34494.0),
("JOAO BATISTA COELHO FILHO", "MARIA FATIMA", "OUTROS CENTROS", 795.0),
("JUN PNEUS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 11132.0),
("KEISE ANGRA COMERCIO E SERVICOS NAU", "MARIA FATIMA", "OUTROS CENTROS", 22377.0),
("KSD OBRAS DE ARTE LTDA", "MARIA FATIMA", "OUTROS CENTROS", 30800.0),
("L.R COMERCIO DE MATERIAIS ELETRICOS", "MARIA FATIMA", "OUTROS CENTROS", 440.0),
("LAB SEG AMBIENTAL LTDA", "MARIA FATIMA", "OUTROS CENTROS", 36700.0),
("LEANDRO A. KORTZ PINTURAS INDUSTRIA", "MARIA FATIMA", "OUTROS CENTROS", 28800.0),
("LEIROZ PNEUS LTDA ME", "MARIA FATIMA", "OUTROS CENTROS", 880.0),
("LIDER PINTURA ELETROSTATICA", "MARIA FATIMA", "OUTROS CENTROS", 36543.0),
("LUCLABARRA COMERCIO DE PLASTICO LTD", "MARIA FATIMA", "OUTROS CENTROS", 4381.0),
("LUMOS PLANEJAMENTO DE COMUNICACAO I", "MARIA FATIMA", "OUTROS CENTROS", 46000.0),
("M AELIAS CONSERVADORA", "MARIA FATIMA", "OUTROS CENTROS", 14760.0),
("MAIS CLEAN LIMPEZA LTDA", "MARIA FATIMA", "OUTROS CENTROS", 34420.0),
("MARCELO MAINARDI FILHO", "MARIA FATIMA", "OUTROS CENTROS", 16254.0),
("MAVS EMPILHADEIRAS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 3583.0),
("MEGATEC ELETROMECANICA LTDA", "MARIA FATIMA", "OUTROS CENTROS", 1008.0),
("MILIARTES ARTES DIGITAIS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 908.0),
("MSOM - LOCACAO DE EQUIPAMENTOS PARA", "MARIA FATIMA", "OUTROS CENTROS", 1050.0),
("NMGOMES MOREIRA", "MARIA FATIMA", "OUTROS CENTROS", 133.0),
("NOVA XTECH", "MARIA FATIMA", "OUTROS CENTROS", 44990.0),
("NRM DA SILVA LTDA", "MARIA FATIMA", "OUTROS CENTROS", 24470.0),
("OUR PEST CONTROL IMUNIZACAO LTDA", "MARIA FATIMA", "OUTROS CENTROS", 27710.0),
("P R CARDOSO E NOVAES LTDA", "MARIA FATIMA", "OUTROS CENTROS", 45881.0),
("P R NORA JUNIOR TERRAPLANAGEM LTDA", "MARIA FATIMA", "OUTROS CENTROS", 22710.0),
("PAPERFLIX INFORMATICA E PAPELARIA L", "MARIA FATIMA", "OUTROS CENTROS", 3353.0),
("POS DADOS COM E SERV DE ASSISTENCIA", "MARIA FATIMA", "OUTROS CENTROS", 270.0),
("PREMIUM EXTINTORES LTDA", "MARIA FATIMA", "OUTROS CENTROS", 656.0),
("PRIMAPOX PINTURAS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 42963.0),
("RANGEL ENGENHARIA E ASSESSORIA TECN", "MARIA FATIMA", "OUTROS CENTROS", 30000.0),
("RCL LETREIROS COMUNICACAO VISUAL LT", "MARIA FATIMA", "OUTROS CENTROS", 13658.0),
("RESEG SOLUCAO EM SEGURANCA", "MARIA FATIMA", "OUTROS CENTROS", 1000.0),
("RODRIGUES LEITE & FEDERLE LTDA - ME", "MARIA FATIMA", "OUTROS CENTROS", 24000.0),
("RONEY SILVA DE ALMEIDA 09547927779", "MARIA FATIMA", "OUTROS CENTROS", 35840.0),
("RUTH MACEDO MONTI SILVA - ESTAQUEAM", "MARIA FATIMA", "OUTROS CENTROS", 24773.0),
("S C M P PINTO INFORMATICA", "MARIA FATIMA", "OUTROS CENTROS", 29674.0),
("S JORGE C MONTEIRO", "MARIA FATIMA", "OUTROS CENTROS", 26725.0),
("S-TECH PRODUTOS INDUSTRIAIS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 25000.0),
("SAMANTA NOGUEIRA DE SOUZA", "MARIA FATIMA", "OUTROS CENTROS", 750.0),
("SANSERVICE MANUTENÇÃO E REPARAÇÃO L", "MARIA FATIMA", "OUTROS CENTROS", 29375.0),
("SCR MAQ SERVICOS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 39910.0),
("SILVA E COIMBRA COM DE BATERIAS LTD", "MARIA FATIMA", "OUTROS CENTROS", 1460.0),
("SUDESTE UNIFORMES COMERCIO E CONFEC", "MARIA FATIMA", "OUTROS CENTROS", 21990.0),
("TECSERV AUTOMACAO LTDA", "MARIA FATIMA", "OUTROS CENTROS", 5280.0),
("TELEMACO FERRAMENTAS COM. DE PECAS", "MARIA FATIMA", "OUTROS CENTROS", 26087.0),
("TRATORIO MAQUINAS AGRICOLAS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 5387.0),
("USE EPI EQUIP SEGURANÇA LTDA", "MARIA FATIMA", "OUTROS CENTROS", 4040.0),
("V R L SERVICOS", "MARIA FATIMA", "OUTROS CENTROS", 39000.0),
("VASCONCELOS ENGENHARIA", "MARIA FATIMA", "OUTROS CENTROS", 25500.0),
("VIDRACARIA PRINCESA DA SERRA LTDA", "MARIA FATIMA", "OUTROS CENTROS", 171.0),
("WESLEY DOS S. SANTIAGO", "MARIA FATIMA", "OUTROS CENTROS", 1002280.0),
("2B CONFECCOES E INDUSTRIA E COMERCI", "MARIA FATIMA", "OUTROS CENTROS", 1480.0),
("38.106.102 JOAO FERNANDO LIMA RODRI", "MARIA FATIMA", "OUTROS CENTROS", 2782.0),
("54.431.923 LEONARDO CORADINE ZAMANS", "MARIA FATIMA", "OUTROS CENTROS", 1397.0),
("59.695.035 MARCELO GUIMARAES", "MARIA FATIMA", "OUTROS CENTROS", 2705.0),
("62.045.410 THIAGO AZEVEDO GONCALVES", "MARIA FATIMA", "OUTROS CENTROS", 2150.0),
("ACM LOCACOES, ESTRUTURAS E SERVICOS", "MARIA FATIMA", "OUTROS CENTROS", 22200.0),
("AEROIND COMERCIAL LTDA", "MARIA FATIMA", "OUTROS CENTROS", 1625.0),
("ALMEIDA COM DE PARAFUSOS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 1680.0),
("ALPHA & OMEGA TRADUCOES LTDA", "MARIA FATIMA", "OUTROS CENTROS", 11500.0),
("ALVARES EQUIPAMENTOS DE SEG E SOLDA", "MARIA FATIMA", "OUTROS CENTROS", 2167.0),
("APARECIDO VALENTIN OSTI", "MARIA FATIMA", "OUTROS CENTROS", 10930.0),
("ARQUIVOS ORGANIZACAO E GESTAO DOCUM", "MARIA FATIMA", "OUTROS CENTROS", 2445.0),
("BARRA IMPORTS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 4999.0),
("BR LED MATERIAS ELETRICOS EIRELI", "MARIA FATIMA", "OUTROS CENTROS", 1693.0),
("BRENFEER E-COMMERCE", "MARIA FATIMA", "OUTROS CENTROS", 787.0),
("BRICKUP LTDA", "MARIA FATIMA", "OUTROS CENTROS", 3000.0),
("CARLOS HENRIQUE DO NASCIMENTO", "MARIA FATIMA", "OUTROS CENTROS", 900.0),
("CHURRASCARIA XALE GRILL LTDA", "MARIA FATIMA", "OUTROS CENTROS", 3432.0),
("COLORGRAF SERVICOS GRAFICOS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 690.0),
("CORTE FACIL PRODUTOS ADESIVOS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 1575.0),
("DACE COMERCIO DE SORVETES LTDA", "MARIA FATIMA", "OUTROS CENTROS", 1687.0),
("DIMAC SOLUCOES INDUSTRIAIS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 19410.0),
("DTF MOVEIS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 615.0),
("DUTRA CORTEZ FILTROS E MANUTENCAO L", "MARIA FATIMA", "OUTROS CENTROS", 3013.0),
("EDMAR GALVAO", "MARIA FATIMA", "OUTROS CENTROS", 1630.0),
("EVOLUCAO SISTEMAS", "JANAINA APARECIDA VENANCIO", "OUTROS CENTROS", 117.0),
("FERNANDA APARECIDA CUNHA DE SOUZA", "MARIA FATIMA", "OUTROS CENTROS", 2230.0),
("FERRAGENS RETIRO DE VOLTA REDONDA L", "MARIA FATIMA", "OUTROS CENTROS", 21222.0),
("FRANCISCO ANTONIO", "MARIA FATIMA", "OUTROS CENTROS", 830.0),
("FUSE ELETRIC", "MARIA FATIMA", "OUTROS CENTROS", 2654.0),
("G LAB BRASIL COMERCIO DE MATERIAIS", "MARIA FATIMA", "OUTROS CENTROS", 1641.0),
("G M ADE BMANSA MAT CONSTLTDA", "MARIA FATIMA", "OUTROS CENTROS", 5643.0),
("GRUPO ROCHA ICOMASAR", "MARIA FATIMA", "OUTROS CENTROS", 4992239.0),
("HOTEL SANTANESIA DE PIRAI LTDA", "MARIA FATIMA", "OUTROS CENTROS", 1738.0),
("HYDROKER-MANUTENCAO HIDRAULICA LTDA", "MARIA FATIMA", "OUTROS CENTROS", 2058.0),
("I C MARCHIORI DE OLIVEIRA HIDRAULIC", "MARIA FATIMA", "OUTROS CENTROS", 2016.0),
("IACRILICOS COMERCIO E SERVIÇOS LTDA", "MARIA FATIMA", "OUTROS CENTROS", 953.0),
("ILUMIRIO ILUMINACAO E ELETRICA LTDA", "MARIA FATIMA", "OUTROS CENTROS", 1586.0),
("INNOVA SAFETY LTDA", "MARIA FATIMA", "OUTROS CENTROS", 2675.0),
("INTERAR COM. E SERVIÇO DE FILTROS L", "MARIA FATIMA", "OUTROS CENTROS", 2070.0),
("ISOLATI ISOLAMENTOS E VEDACOES LTDA", "MARIA FATIMA", "OUTROS CENTROS", 1600.0),
("IZAURA MARIA DE ALMEIDA FERREIRA", "MARIA FATIMA", "OUTROS CENTROS", 1120.0),
("J. CHIQUITTO IND E COM E EXP LTDA", "MARIA FATIMA", "OUTROS CENTROS", 1890.0),
("JC SOLUCOES INTEGRADAS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 2058.0),
("JGG DE CASTRO AUTO MECANICA ME", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 2445.0),
("JOSE MARCOS", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1350.0),
("K M H COMERCIO DE MAQUINAS E EQUIPA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1552.0),
("KAIRON ISIDIO CUNHA 51.172.934", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 550.0),
("LABOR SHOPING COMERCIO DE PRODUTOS", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 133.0),
("LIMP SERVICE VR LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 4800.0),
("LUIS AUGUSTO SPRANGER LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 285.0),
("M S DE ALMEIDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 2015.0),
("M.F.OLIVEIRA BORRACHAS LTDA.", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 568.0),
("MALTA, ROSA & PARTNERS OUTSOURCING", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 2900.0),
("MANGOTEC COMMANG EQUIP INDLTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1598.0),
("MARMORARIA DO ANIL LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1950.0),
("MAXIMUS SECURITY EQ PROT E MAT ELET", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1020.0),
("MECANICA IMATA LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1673.0),
("MEH LIMPEZA HIGIENIZACAO", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 600.0),
("MINAS FLEXX CORTINAS FLEXIVEIS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1200.0),
("MULTILOC ALUGUEL DE FERRAMENTAS LTD", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 190.0),
("NAUTICA REIS COMERCIO E SERVICO LTD", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1693.0),
("NDE LPAULO LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1674.0),
("NORTE MADEIRAS MAT. DE CONSTRUCAO L", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1980.0),
("OLIVEIRA E MELO SERVICOS E COMERCIO", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 15000.0),
("PADARIA E CONFEITARIA FAJARDO - SAO", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1637.0),
("PATRICIA S BARBOSA CALCADOS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 323.0),
("POST BANK COMSERVE ASSISTECLTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 4218.0),
("PRODUTECH MAQUINAS  E EQUIPAMENTOS", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 600.0),
("PROJETEE ENGENHARIA E PROJETOS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1800.0),
("REAL SINALIZACAO IND.COM. E SERVICO", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 697.0),
("REMAP MANUTENCAO DE MAQUINAS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 2700.0),
("RINALDO MAZZA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 590.0),
("RIVATERM TERMOMETROS E DENS. IND EI", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1912.0),
("SANDRA APARECIDA LIMA DA CRUZ SOUZA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 2010.0),
("SANDRA AUREA HAMZEH COMERCIO", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 196.0),
("SENSORES INDUSTRIAIS", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 2302.0),
("SER SERVICOS ESPECIALIZADOS EM REUS", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1796.0),
("SINALOJA COMERCIO VAREJISTA LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 155.0),
("SJS SOMANDO BALANCAS IND COM LTDA.", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 2703.0),
("SUPRIMENTOS BRASIL", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 2610.0),
("SUZANA RODRIGUES DE", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 600.0),
("TESHOP COMERCIO", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 177.0),
("THAIANNE COSTA LUIZ 15008081721", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1620.0),
("THOR MARINE LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1889.0),
("TRIUNFADEX INDUSTRIA E COM DE METAL", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 400.0),
("VAL DBJ SERVICOS E PRODUTOS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1500.0),
("VM DISTRIBUIDORA DE PECAS INDUSTRIA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 450.0),
("WDM COMERCIAL LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 2144.0),
("WMB SERVICOS DE REPARACAO", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 2700.0),
("X10 ACELERADORA DE NEG. E INVEST. L", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1577.0),
("Y CBARTA PURIFICADORES DE AGUA E BE", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 2636.0),
("ZIMAX COMERCIO E SERVICOS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1118.0),
("ÁGUAS SUL", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 3000.0),
("2TALK COMUNICACOES INTEGRADAS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1439.0),
("54.987.822", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 83.0),
("ADVANCE ASSESSORIA E CONTABILIDADE", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 5025.0),
("ALPHA-FER COM E IND LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 264.0),
("ARAUJO E FILHO COMERCIO DE FERRAGEN", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 254.0),
("ASCH ENGENHARIA E PROJETOS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 477115.0),
("BARRA REAL TINTAS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 16228.0),
("BARRA REFRIGERACOES MANUTENCAO ELET", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 426750.0),
("BRV VENDAS DIGITAIS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 3148.0),
("CASA DO NEON LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1200.0),
("CILWORK MANUTENCAO INDUSTRIAL LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 11100.0),
("CONSERTAR COMERCIO E MANUTENCAO", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 741.0),
("DIMASEG DISTDE MATERIAL DE SEGLTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 22001.0),
("E.J PRODUTOS P/ SEG. DE EMBALAGENS", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 14680.0),
("ELO SERVICOS ESPECIALIZADOS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 421729.0),
("EZEMAC MULTI UTILIDADES LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 3288.0),
("FRIAS E TOME SOLUCOES INDUSTRIAIS L", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 20966.0),
("G N DE MELO PCS ACES VEIC AUTOMOTOR", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 237.0),
("H MARTINS CONFORT JUNIOR", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 11730.0),
("HALLON SECURITY", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 710300.0),
("J ARANTES PROJETOS E", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 16750.0),
("JOSE ROBERTO MOUTINHO PEREIRA 00009", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 340.0),
("KARVI SERVICO E MANUTENCAO LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 14345.0),
("LAURA DAS GRACAS DUQUE DE FREITAS S", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1010778.0),
("LIVRARIA EVANGELICA REMA LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 188.0),
("LUIZ FERREIRA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1000.0),
("MAC MANUTENCAO INDUSTRIAL LOCSERVEI", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 387986.0),
("MADEIREIRA IRMAOS ROCHA E OLIVEIRA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 885.0),
("MARCIO ANDRE TEIXEIRA DE GODOY", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1520.0),
("MDO INDUSTRIA E COMERCIO LTDA ME", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1288.0),
("MEMORIAL PARTS", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 469.0),
("MIQUELETTO ENGENHARIA LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 527.0),
("N. D. COSTA MATERIAL DE CONSTRUCAO", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 960.0),
("ONIX ROLAMENTOS E", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 5400.0),
("ONOFRE J.SOUZA ME", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 743928.0),
("PAULO DOMINGOS", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 103.0),
("POSTES RIO", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 22006.0),
("R G B MOURA SERVICOS GRAFICOS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 15925.0),
("RECALL INFORMATICA E COM. CARTUCHO", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 127.0),
("RLAR SERVICOS DE DECORACOES LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 3104.0),
("SANTOS E SILVEIRA COMERCIO DE EQUIP", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1515.0),
("SOLDOR EQUIPAMENTOS PARA SOLDAGEM", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 959.0),
("SXS VENDAS E", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 620.0),
("TI NEVES AUTO PECAS LTDA - ME", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 12800.0),
("TSS PECAS E SERVICOS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 5284.0),
("VEGAS TECNOLOGIA E SISTEMAS", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 1017.0),
("VULCANSHOP MOTO PECAS", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 44.0),
("ZIMPOR COMERCIO DE PRODUTOS LTDA", "RAFAEL NASCIMENTO", "OUTROS CENTROS", 110.0),
]

# =============================================================================
# BLOCO 2 - FUNÇÕES DE BANCO
# =============================================================================
def init_db():
    id_col = "id INTEGER PRIMARY KEY AUTOINCREMENT" if IS_SQLITE else "id SERIAL PRIMARY KEY"
    try:
        with engine.begin() as conn:
            conn.execute(text(f"""
                CREATE TABLE IF NOT EXISTS contatos (
                    {id_col},
                    comprador TEXT, fornecedor TEXT, categoria TEXT,
                    cnpj TEXT, contato TEXT,
                    recebeu TEXT, fala_contador TEXT,
                    previsao_retorno TEXT, status TEXT, observacao TEXT
                );
            """))
    except Exception as e:
        st.error(f"Erro banco: {e}")
        st.stop()

    novas = {
        "cnpj": "TEXT",
        "data_contato": "TEXT",
        "canal_contato": "TEXT",
        "reenvio_necessario": "TEXT",
        "acompanha_reforma": "INTEGER DEFAULT 0",
        "discutiu_internamente": "INTEGER DEFAULT 0",
        "falou_contador": "INTEGER DEFAULT 0",
        "responsavel_contador": "TEXT",
        "definicao_2027": "TEXT",
        "data_proximo_contato": "TEXT",
        "proxima_acao": "TEXT",
        "canal": "TEXT",
        "recebeu_comunicado": "TEXT",
        "spend_float": "REAL",
        "spend_anual": "TEXT",
    }
    with engine.begin() as conn:
        for col, tipo in novas.items():
            try:
                conn.execute(text(f"ALTER TABLE contatos ADD COLUMN {col} {tipo}"))
            except:
                pass

def seed():
    with engine.connect() as conn:
        try:
            count = conn.execute(text("SELECT COUNT(*) FROM contatos")).scalar()
            if count == 606:
                return
            elif count and count != 606:
                with engine.begin() as c2:
                    c2.execute(text("DELETE FROM contatos"))
        except:
            pass

    df = pd.DataFrame(DADOS_606_BALANCEADO, columns=["fornecedor","comprador","categoria","spend_float"])
    df = df.sort_values(by="spend_float", ascending=False)
    df["spend_anual"] = df["spend_float"].apply(lambda x: f"R$ {x:,.2f}".replace(",", "X").replace(".", ",").replace("X", "."))
    df["cnpj"] = ""
    df["contato"] = ""
    df["data_contato"] = "23/07/2026"
    df["canal_contato"] = "LIGAÇÃO/WHATS"
    df["recebeu"] = "Pendente"
    df["reenvio_necessario"] = "Não"
    df["acompanha_reforma"] = 0
    df["discutiu_internamente"] = 0
    df["falou_contador"] = 0
    df["responsavel_contador"] = ""
    df["definicao_2027"] = "Em análise"
    df["previsao_retorno"] = "10/07/2026"
    df["data_proximo_contato"] = "10/07/2026"
    df["status"] = "Laranja"
    df["proxima_acao"] = "Aguardar retorno"
    df["observacao"] = ""
    try:
        df.to_sql("contatos", engine, if_exists="append", index=False)
    except Exception as e:
        st.warning(f"Erro seed: {e}")

init_db()
seed()

try:
    with engine.connect() as conn:
        total_login = conn.execute(text("SELECT COUNT(*) FROM contatos")).scalar() or 0
        atend_login = conn.execute(text("SELECT COUNT(*) FROM contatos WHERE status NOT IN ('', 'Pendente', 'None') AND status IS NOT NULL AND status != '' AND status != 'Laranja' AND status != 'Pendente - Fornecedor Não contatado'")).scalar() or 0
        perc_login = (atend_login / total_login * 100) if total_login else 0
except:
    total_login = 0
    atend_login = 0
    perc_login = 0

# =============================================================================
# BLOCO 3 - USUÁRIOS
# =============================================================================
USUARIOS = {
    "Camila": {"senha": "Camila@2026", "nome_completo": "CAMILA CAROLINE DA SILVA"},
    "Gilcimar": {"senha": "Gil@2026", "nome_completo": "GILCIMAR SILVA"},
    "Janaina": {"senha": "Jana@2026", "nome_completo": "JANAINA APARECIDA VENANCIO"},
    "Maria Fatima": {"senha": "Fatima@2026", "nome_completo": "MARIA FATIMA"},
    "Rafael": {"senha": "Rafa@2026", "nome_completo": "RAFAEL NASCIMENTO"},
    "Waldecir": {"senha": "Wal@2026", "nome_completo": "WALDECIR MARQUES"},
    "Gestão": {"senha": "Mbp@Gestao2026", "nome_completo": "GESTÃO"},
}
COMPRADORES_CURTO = ["Camila", "Gilcimar", "Janaina", "Maria Fatima", "Rafael", "Waldecir", "Gestão"]
MAP_COMPRADOR = {k: v["nome_completo"] for k, v in USUARIOS.items()}
KEY_MAP = {
    "Camila": "perf_Camila", "Gilcimar": "perf_Gilcimar", "Janaina": "perf_Janaina",
    "Maria Fatima": "perf_Maria", "Rafael": "perf_Rafael", "Waldecir": "perf_Waldecir",
    "Gestão": "perf_Gestao",
}

if "autenticado" not in st.session_state:
    st.session_state.autenticado = False
if "usuario_logado" not in st.session_state:
    st.session_state.usuario_logado = None
if "perfil" not in st.session_state:
    st.session_state.perfil = "Camila"
if "trocando_perfil" not in st.session_state:
    st.session_state.trocando_perfil = False

def fazer_login(u, p):
    if u in USUARIOS and USUARIOS[u]["senha"] == p:
        st.session_state.autenticado = True
        st.session_state.usuario_logado = u
        st.session_state.perfil = u
        return True
    return False

# =============================================================================
# BLOCO 4 - LOGIN
# =============================================================================
if not st.session_state.autenticado:
    st.set_page_config(page_title="Login - MBP 606 - 101 cada", layout="wide")
    st.markdown("""
    <style>
    #MainMenu, footer, header {visibility: hidden;}
    .stApp { background: #08162E !important; }
    .block-container { padding-top: 0 !important; max-width: 100% !important; }
    .login-card { background:#0F2242; border:1px solid #1E3A5F; border-radius:16px; padding:28px 26px; }
    div[data-testid="stSelectbox"] label, div[data-testid="stTextInput"] label { color:#8BA3C7 !important; font-size:11px !important; }
    div[data-baseweb="select"] > div { background:#132A4E !important; border:1px solid #1E3A5F !important; border-radius:8px !important; color:white !important; }
    div[data-baseweb="select"] span { color:white !important; }
    div[data-testid="stTextInput"] input { background:#132A4E !important; color:white !important; border:1px solid #1E3A5F !important; border-radius:8px !important; }
    div[data-testid="stButton"] > button[kind="primary"] { background:#ffc000 !important; color:#08162E !important; border-radius:8px !important; font-weight:800 !important; height:44px !important; }
    </style>
    """, unsafe_allow_html=True)
    left, right = st.columns([1.4, 0.75], gap="large")
    with left:
        st.markdown(f"""
        <div style="padding: 28px 20px 20px 48px;">
            <div style="display:inline-flex; align-items:center; gap:10px; background: rgba(255,192,0,0.12); border:1px solid rgba(255,192,0,0.25); padding:9px 16px; border-radius:24px; margin-bottom:26px;">
                <span style="color:#ffc000; font-size:12px; font-weight:800;">GRUPO MBP • 606 FORNECEDORES • 101 CADA • SO SPEND</span>
            </div>
            <div style="font-size:52px; font-weight:900; color:white; line-height:0.92; margin-bottom:20px;">Organize com<br>clareza.<br>Entregue com<br><span style="color:#ffc000;">segurança.</span></div>
            <div style="display:flex; gap:14px;"><div style="flex:1; background:#0F2242; border:1px solid #1E3A5F; border-radius:14px; padding:16px;">
                <div style="color:#ffc000; font-size:11px; font-weight:800; margin-bottom:12px;">📊 VISÃO DA CAMPANHA - 606 BALANCEADO</div>
                <div style="display:flex; justify-content:space-between; margin-bottom:8px;"><span style="color:#8BA3C7; font-size:12px;">Fornecedores contatados</span><span style="color:white; font-size:12px; font-weight:700;">{perc_login:.1f}%</span></div>
                <div style="background:#08162E; height:6px; border-radius:3px; overflow:hidden;"><div style="background:#ffc000; width:{perc_login}%; height:100%;"></div></div>
                <div style="color:#5A7AA8; font-size:10px; margin-top:8px;">{atend_login} de {total_login} • 101 cada comprador</div>
            </div></div>
        </div>
        """, unsafe_allow_html=True)
    with right:
        st.markdown('<div class="login-card">', unsafe_allow_html=True)
        st.markdown("""<div style="color:white; font-size:20px; font-weight:800; margin-bottom:6px;">Bem-vindo de volta</div><div style="color:#5A7AA8; font-size:12px; margin-bottom:22px;">Use seu usuário de comprador</div>""", unsafe_allow_html=True)
        usuario_sel = st.selectbox("Usuário", COMPRADORES_CURTO, key="login_user_fix")
        senha_input = st.text_input("Senha", type="password", placeholder="Digite sua senha", key="login_pass_fix")
        if st.button("Entrar no portal →", use_container_width=True, type="primary", key="btn_login_fix"):
            if fazer_login(usuario_sel, senha_input):
                st.rerun()
            else:
                st.error("Senha incorreta")
        st.markdown('</div>', unsafe_allow_html=True)
    st.stop()

# =============================================================================
# BLOCO 5 - TELA PRINCIPAL
# =============================================================================
@st.cache_data(ttl=30, show_spinner=False)
def carregar_contatos():
    df = pd.read_sql(text("SELECT * FROM contatos"), engine).fillna("")
    if "spend_float" in df.columns:
        df["spend_float"] = pd.to_numeric(df["spend_float"], errors='coerce').fillna(0)
        df = df.sort_values(by="spend_float", ascending=False)
    return df

perfil_curto = st.session_state.perfil

if st.session_state.trocando_perfil:
    time.sleep(0.3)
    carregar_contatos.clear()
    st.session_state.trocando_perfil = False
    st.rerun()

st.markdown("""
<style>
#MainMenu, footer, header {visibility: hidden;}
.stApp { background: #F6F7F9 !important; }
.block-container { max-width: 100% !important; padding-top: 1rem !important; }
section[data-testid="stSidebar"] { background-color: #0F172A !important; }
.badge { font-size:11px; font-weight:600; padding:5px 10px; border-radius:20px; border:1px solid;}
.badge-Verde { background:#ECFDF5; color:#065F46; border-color:#A7F3D0;}
.badge-Amarelo { background:#FEFCE8; color:#854D0E; border-color:#FDE68A;}
.badge-Laranja { background:#FFF7ED; color:#9A3412; border-color:#FDBA74;}
.badge-Vermelho { background:#FEF2F2; color:#991B1B; border-color:#FECACA;}
.badge-Cinza { background:#F3F4F6; color:#374151; border-color:#D1D5DB;}
.badge-Pendente { background:#F9FAFB; color:#6B7280; border-color:#E5E7EB;}
label { font-size:11px !important; font-weight:600 !important; color:#111827 !important;}
div[data-testid="stExpander"] { background:white !important; border:1px solid #D1D5DB !important; border-radius:14px !important; margin-bottom:8px !important; }
</style>
""", unsafe_allow_html=True)

df_all = carregar_contatos()

with st.sidebar:
    st.markdown(f'''<div style="color:#FFC107; font-weight:800;">MBP • Campanha<br><span style="font-size:11px;">606 • 101 cada • Só SPEND</span></div><div style="background:#1E293B; padding:10px; border-radius:10px; color:#94A3B8; font-size:12px; margin-top:10px;">Logado: <b style="color:#FFC107;">{st.session_state.usuario_logado}</b><br>{len(df_all)} fornecedores</div>''', unsafe_allow_html=True)
    st.markdown("---")
    for nome in COMPRADORES_CURTO:
        if st.button(nome, key=KEY_MAP[nome], use_container_width=True):
            if nome != st.session_state.perfil:
                st.session_state.perfil = nome
                st.session_state.trocando_perfil = True
                st.rerun()
    if st.button("Sair", use_container_width=True):
        st.session_state.autenticado=False
        st.rerun()

perfil_real = MAP_COMPRADOR[perfil_curto]

if perfil_curto == "Gestão":
    st.markdown(f"### Gestão • {len(df_all)} fornecedores • 101 cada • Ordenado por SPEND")
    cols_show = ["fornecedor","comprador","categoria","spend_anual","status"]
    cols_show = [c for c in cols_show if c in df_all.columns]
    st.dataframe(df_all[cols_show].sort_values(by="spend_float" if "spend_float" in df_all.columns else "fornecedor", ascending=False), use_container_width=True, height=600)
    st.stop()

df = df_all[df_all["comprador"] == perfil_real].copy()
df = df.sort_values(by="spend_float", ascending=False)
total = len(df)
cont = len(df[~df["status"].isin(["", "Pendente", "None", "Pendente - Fornecedor Não contatado"])])
perc = cont / total * 100 if total else 0
st.markdown(f"### Fornecedores • {perfil_curto} • {total} fornecedores • {perc:.1f}% concluído • 101 cada • Ordenado por SPEND")

busca = st.text_input("🔍 Buscar fornecedor rápido:", placeholder="Ex: GRUPO ROCHA")
if busca:
    df = df[df["fornecedor"].str.lower().str.contains(busca.lower(), na=False)]

col_left, col_right = st.columns(2)
OPCOES_PROXIMA_ACAO = ["Nenhuma", "Aguardar retorno", "Reenviar e-mail", "Escalar p/ Fiscal"]

for idx, (i,row) in enumerate(df.iterrows()):
    target = col_left if idx %2==0 else col_right
    badge = row.get("status") or "Pendente"
    spend_txt = row.get("spend_anual") or ""
    icon = "🟢" if "Verde" in badge else "🔴" if "Vermelho" in badge else "🟠" if "Laranja" in badge else "⚪"
    titulo = f"{icon} {row.get('fornecedor')} • {spend_txt} • {badge}"
    with target:
        with st.expander(titulo, expanded=False):
            st.markdown(f"**{row.get('fornecedor')}** - {row.get('categoria')} - **{spend_txt}**")
            with st.form(key=f"form_{idx}_{row['id']}"):
                c1,c2 = st.columns(2)
                with c1:
                    val = row.get("data_contato")
                    di = None
                    if val and str(val).strip()!="":
                        try: di = datetime.strptime(str(val).strip(), "%d/%m/%Y").date()
                        except: pass
                    dc_obj = st.date_input("DATA DO CONTATO", value=di, format="DD/MM/YYYY", key=f"dc_{idx}_{row['id']}")
                    dc = dc_obj.strftime("%d/%m/%Y") if dc_obj else ""
                with c2:
                    canal = st.selectbox("CANAL", ["LIGAÇÃO/WHATS","E-MAIL","REUNIÃO","OUTRO"], key=f"ca_{idx}_{row['id']}")
                c3,c4 = st.columns(2)
                with c3:
                    recebeu = st.selectbox("RECEBEU COMUNICADO?", ["Pendente","Sim","Não"], key=f"re_{idx}_{row['id']}")
                with c4:
                    reenvio = st.selectbox("REENVIO NECESSÁRIO?", ["Não","Sim"], key=f"rn_{idx}_{row['id']}")
                chk1 = st.checkbox("Já acompanha Reforma?", value=bool(row.get("acompanha_reforma",0)), key=f"chk1_{idx}_{row['id']}")
                chk2 = st.checkbox("Já discutiu internamente?", value=bool(row.get("discutiu_internamente",0)), key=f"chk2_{idx}_{row['id']}")
                chk3 = st.checkbox("Já falou c/ contador?", value=bool(row.get("falou_contador",0)), key=f"chk3_{idx}_{row['id']}")
                c5,c6 = st.columns(2)
                with c5:
                    resp = st.text_input("RESPONSÁVEL INTERNO / CONTADOR", value=str(row.get("responsavel_contador") or ""), key=f"resp_{idx}_{row['id']}")
                with c6:
                    def_2027 = st.selectbox("DEFINIÇÃO PRELIMINAR 2027", ["Em análise","Manter Simples Nacional","Migrar para Simples Híbrido","Migrar para Lucro Presumido","Migrar para Lucro Real","Aguardando orientação contábil","Ainda sem definição","Não informado"], key=f"def_{idx}_{row['id']}")
                c7,c8 = st.columns(2)
                with c7:
                    prev = st.text_input("PREVISÃO RETORNO", value=str(row.get("previsao_retorno") or "10/07/2026"), key=f"prev_{idx}_{row['id']}")
                with c8:
                    prox = st.text_input("DATA PRÓXIMO CONTATO", value=str(row.get("data_proximo_contato") or "10/07/2026"), key=f"prox_{idx}_{row['id']}")
                c9,c10 = st.columns(2)
                with c9:
                    status = st.selectbox("STATUS OFICIAL", ["Pendente - Fornecedor Não contatado","Verde -Confirmado","Amarelo - Em avaliação","Laranja - Sem definição","Vermelho - - Não pretende alterar","Cinza - Não localizado"], key=f"st_{idx}_{row['id']}")
                with c10:
                    pa = st.selectbox("PRÓXIMA AÇÃO", OPCOES_PROXIMA_ACAO, key=f"pa_{idx}_{row['id']}")
                obs = st.text_area("OBSERVAÇÃO + EVIDÊNCIAS", value=str(row.get("observacao") or ""), key=f"obs_{idx}_{row['id']}", height=70)
                submitted = st.form_submit_button("💾 SALVAR", use_container_width=True)
                if submitted:
                    try:
                        with engine.begin() as conn:
                            conn.execute(text("UPDATE contatos SET data_contato=:dc, canal_contato=:cc, recebeu=:r, reenvio_necessario=:rn, acompanha_reforma=:ar, discutiu_internamente=:di, falou_contador=:fc, responsavel_contador=:rc, definicao_2027=:d27, previsao_retorno=:p, data_proximo_contato=:dpc, status=:s, proxima_acao=:pa, observacao=:o WHERE id=:id"),
                                {"dc":dc,"cc":canal,"r":recebeu,"rn":reenvio,"ar":1 if chk1 else 0,"di":1 if chk2 else 0,"fc":1 if chk3 else 0,"rc":resp,"d27":def_2027,"p":prev,"dpc":prox,"s":status,"pa":pa,"o":obs,"id":int(row['id'])})
                        carregar_contatos.clear()
                        st.success("SALVO!")
                        time.sleep(0.3)
                        st.rerun()
                    except Exception as e:
                        st.error(f"ERRO: {e}")
